version: "3"

services:
  postgres:
    image: postgis/postgis
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: cdf
      POSTGRES_PASSWORD: insecure
      SSLMODE: "disable"

  tiles:
    image: pramsey/pg_tileserv:20210421
    ports:
      - "7800:7800"
    links:
      - postgres
    volumes:
      - ./config:/app/config
    environment:
      DATABASE_URL: postgresql://cdf:insecure@postgres:5432/test

  api:
    build: ./vng
    ports:
      - "8000:8000"
    links:
      - postgres
    environment:
      - DB_NAME=test
      - DB_USER=cdf
      - DB_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/vng/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES="/* 3600"
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=vng.wsgi:application
      - DJANGO_SETTINGS_MODULE=vng.settings
    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    command: uwsgi --py-auto-reload=1