version: "3"

services:
  postgres:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: cdf
      POSTGRES_PASSWORD: insecure
      SSLMODE: "disable"

  tiles:
    image: pramsey/pg_tileserv:20210421
    ports:
      - "7800:7800"
    links:
      - postgres
    volumes:
      - ./config:/app/config
    environment:
      DATABASE_URL: postgresql://cdf:insecure@postgres:5432/test

  api:
    build: ./vng
    ports:
      - "8000:8000"
    links:
      - postgres
    env_file:
      - ./.env.dev
    volumes:
      - ./api/app:/app
      - ./api/deploy:/deploy
    # command: uwsgi --py-auto-reload=1
    command: python manage.py runserver 0.0.0.0:8000
