# Generated by Django 4.1.2 on 2022-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlateCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_api_company_name', models.CharField(max_length=255, null=True)),
                ('bovag_matched_name', models.CharField(max_length=255, null=True)),
                ('poitive_reviews', models.IntegerField(null=True)),
                ('negative_reviews', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('duplicate_location', models.CharField(max_length=50, null=True)),
                ('kvk_tradename', models.TextField(null=True)),
                ('irregularities', models.CharField(max_length=50, null=True)),
                ('duplicates_found', models.CharField(max_length=50, null=True)),
                ('Bovag_registered', models.CharField(max_length=50, null=True)),
                ('KVK_found', models.CharField(max_length=50, null=True)),
                ('company_ratings', models.CharField(max_length=50, null=True)),
                ('license_number', models.TextField(null=True)),
                ('image', models.FileField(upload_to='media/')),
            ],
        ),
    ]
