# Generated by Django 4.1.2 on 2022-11-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_api_company_name', models.CharField(max_length=255, null=True)),
                ('bovag_matched_name', models.CharField(max_length=255, null=True)),
                ('poitive_reviews', models.IntegerField(null=True)),
                ('negative_reviews', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('duplicate_location', models.CharField(max_length=50, null=True)),
                ('kvk_tradename', models.TextField(null=True)),
                ('irregularities', models.CharField(max_length=50, null=True)),
                ('duplicates_found', models.CharField(max_length=50, null=True)),
                ('Bovag_registered', models.CharField(max_length=50, null=True)),
                ('KVK_found', models.CharField(max_length=50, null=True)),
                ('company_ratings', models.CharField(max_length=50, null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='TargetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('target_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.targetimage')),
            ],
        ),
    ]
