# Generated by Django 4.1.2 on 2022-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
