# Generated by Django 4.1.2 on 2022-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Bovag_registered',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='KVK_found',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bovag_matched_name',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_ratings',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='duplicate_location',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='duplicates_found',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='irregularities',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='kvk_tradename',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='negative_reviews',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='place_api_company_name',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='poitive_reviews',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='license_number',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
