# Generated by Django 4.1.2 on 2022-12-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='datetime2',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
