# Generated by Django 4.1.2 on 2022-11-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplatecompanydata',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenseplatecompanydata',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
