# Generated by Django 4.1.2 on 2022-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_history_datetime_history_datetime2'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time2',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
