# Generated by Django 4.1.2 on 2022-12-19 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_company_datetime_new_history_datetime_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='datetime_new',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 56, 31, 333490, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='datetime_new',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 56, 31, 333490, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='datetime_new',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 56, 31, 333490, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='targetimage',
            name='datetime_new',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 56, 31, 333490, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
