# Generated by Django 4.1.2 on 2022-11-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_targetimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
