# Generated by Django 4.1.2 on 2022-12-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_history_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='history',
            name='datetime2',
        ),
        migrations.RemoveField(
            model_name='history',
            name='time2',
        ),
    ]
