# Generated by Django 4.1.2 on 2022-11-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_company_bovag_registered_and_more'),
        ('base', 'custom_migration'),
    ]

    operations = [
    ]
