# Generated by Django 4.1.2 on 2022-12-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_history_datetime_remove_history_datetime2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
