# Generated by Django 4.1.2 on 2022-11-23 10:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_worldborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
