# Generated by Django 4.1.2 on 2022-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_company_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='createdAt',
            field=models.TimeField(auto_now=True),
        ),
    ]
