# Generated by Django 4.1.2 on 2022-11-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_company_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
        migrations.AlterField(
            model_name='company',
            name='createdAt',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
