# Generated by Django 4.1.2 on 2022-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_worldborder_alter_company_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetimage',
            name='image_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
